version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=car-shop
    ports:
      - "5432:5432"
    networks:
      - backend
  cs-server:
    container_name: cs-server
    build:
      context: .
      dockerfile: Dockerfile
    image: cs-server:0.0.1
    ports:
      - "3000:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/car-shop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - backend
  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
      - cs-server
    command: >
      bash -c "sleep 30 && liquibase
      --hub-mode=off
      --changelog-file=master.xml
      --driver=org.postgresql.Driver
      --url=jdbc:postgresql://postgres:5432/car-shop
      --username=postgres
      --password=postgres
      --searchPath=/liquibase/changelog
      update"
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend
networks:
  backend:
    driver: bridge
